version: '3'
volumes:
    db-store:
    php-fpm-socket:
services:
    web:
        build: ./docker/apache
        image: apache-dev
        ports:
            - 8888:80
        volumes:
            - ./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
            - ./app/dist:/webroot
    db:
        build: ./docker/mysql
        image: mysql-dev
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: devdb
            MYSQL_USER: dev
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
            TZ: 'Asia/Tokyo'
        volumes:
            - db-store:/var/lib/mysql
    php:
        build: ./docker/php
        image: php-dev
        volumes:
            - php-fpm-socket:/var/run/php-fpm
            - ./app/dist:/webroot
