version: '3'
volumes:
    db-store:
    php-fpm-socket:
services:
    web:
        build: ./docker/nginx
        ports:
            - 8888:80
        volumes:
            - php-fpm-socket:/var/run/php-fpm
            - ./app/dist:/webroot
    db:
        build: ./docker/mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: devdb
            MYSQL_USER: dev
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
            TZ: 'Asia/Tokyo'
        volumes:
            - db-store:/var/lib/mysql
    php:
        build: ./docker/php
        volumes:
            - php-fpm-socket:/var/run/php-fpm
            - ./app/dist:/webroot
